package com.edubridge.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "quiz_attempts", 
       uniqueConstraints = {@UniqueConstraint(columnNames = {"syncUuid"})})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class QuizAttempt {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Idempotency token generated by client
    @Column(nullable = false, unique = true)
    private String syncUuid;

    @Column(name = "student_id", nullable = false)
    private Long studentId;

    @Column(name = "quiz_id", nullable = false)
    private Long quizId;

    private int score;
    private int maxScore;

    @Column(columnDefinition = "TEXT")
    private String answersJson;

    @Column(nullable = false)
    private Long attemptTimestamp;
}
