import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def ai_chat(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            prompt = data.get('prompt', '').lower()
            
            # Simulated AI / Offline Fallback logic
            if 'quiz' in prompt:
                response_text = "Here is a quick quiz generated by the EduBridge Offline AI:\n1. What is the capital of France?\n2. What is 5 + 7?"
            elif 'explain' in prompt:
                response_text = "EduBridge Offline AI Explanation: This concept means that you are learning something new. Let's break it down into smaller, easy-to-understand parts..."
            else:
                response_text = "EduBridge AI Fallback: I am currently running in offline mode. I can generate quizzes or explain concepts if you ask!"
                
            return JsonResponse({'response': response_text})
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=400)
    return JsonResponse({'error': 'Only POST allowed'}, status=405)
